app = "mastodon-example"

kill_signal = "SIGINT"
kill_timeout = 5

## Uncomment if you are upgrading Mastodon. See README.md for details.
# [deploy]
#   release_command = "bin/rails db:migrate"

[env]
  LOCAL_DOMAIN = "mastodon-example.fly.dev"
  MALLOC_ARENA_MAX = "2"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "enabled"
  RAILS_SERVE_STATIC_FILES = "false"
  WEB_CONCURRENCY = "0"
  REDIS_HOST = "mastodon-example-redis.internal"
  REDIS_PORT = "6379"
  ## Storage on S3 also requires secrets named AWS_ACCESS_KEY_ID and 
  ## AWS_SECRET_ACCESS_KEY. If you use this, remove [mounts] below.
  # S3_ENABLED=true
  # S3_BUCKET=mastodon-example-bucket
  ## If you point to Fly here, uncomment the proxy in Caddyfile
  # S3_ALIAS_HOST=mastodon-example.fly.dev
  ## Sending email via SMTP also requires secrets
  ## named SMTP_LOGIN and SMTP_PASSWORD
  # SMTP_SERVER = "smtp.postmarkapp.com"
  # SMTP_PORT = "587"
  # SMTP_ENABLE_STARTTLS = "always"
  # SMTP_FROM_ADDRESS = "admin@mastodon.fly.dev"

## Comment out this section if you use cloud storage
[mounts]
  source = "mastodon_uploads"
  destination = "/opt/mastodon/public/system"

[[statics]]
  guest_path = "/opt/mastodon/public"
  url_prefix = "/"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    path = "/health"
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
