app = "mastodon"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  LOCAL_DOMAIN = "mastodon.example.com"
  DB_HOST = "mastodon-db.internal"
  DB_USER = "postgres"

[mounts]
  source = "mastodon_data"
  destination = "/opt/mastodon/public/system"

[processes]
  app = "env REDIS_URL=$FLY_REDIS_CACHE_URL bundle exec rails s -p 3000"

[[statics]]
  guest_path = "/opt/mastodon/public"
  url_prefix = "/"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    path = "/health"
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
