app = "mastodon"

kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "bin/rails db:migrate"

[env]
  LOCAL_DOMAIN = "mastodon.fly.dev"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "enabled"
  RAILS_SERVE_STATIC_FILES = "false"
  WEB_CONCURRENCY = "1"
  REDIS_HOST = "mastodon-redis.internal"
  REDIS_PORT = "6379"
  ## Storage on S3 also requires secrets named
  ## AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
  # S3_ENABLED=true
  # S3_BUCKET=files.example.com
  # S3_ALIAS_HOST=files.example.com
  ## Sending email via SMTP also requires secrets
  ## named SMTP_LOGIN and SMTP_PASSWORD
  # SMTP_SERVER = "smtp.postmarkapp.com"
  # SMTP_PORT = "587"
  # SMTP_ENABLE_STARTTLS = "always"
  # SMTP_FROM_ADDRESS = "admin@mastodon.fly.dev"

[mounts]
  source = "mastodon_uploads"
  destination = "/opt/mastodon/public/system"

[[statics]]
  guest_path = "/opt/mastodon/public"
  url_prefix = "/"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    path = "/health"
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
