app = "mastodon-3615-computer"

kill_signal = "SIGINT"
kill_timeout = 5
swap_size_mb = 1024

[deploy]
strategy = "bluegreen"
## Uncomment if you are upgrading Mastodon. See README.md for details.
# release_command = "bin/rails db:migrate"

[env]
# Sources:
# - https://github.com/mastodon/mastodon/blob/3abb5c0eaabb408337bcd2b9a36cf1d8527f467e/dist/mastodon-web.service#L11
# - https://leah.is/posts/scaling-the-mastodon/
LOCAL_DOMAIN = "3615.computer"
WEB_CONCURRENCY = "4"
MAX_THREADS = "5"
OVERMIND_FORMATION = "sidekiq=1"
# MALLOC_ARENA_MAX = "2" // Replaced with "LD_PRELOAD=libjemalloc.so"
LD_PRELOAD = "libjemalloc.so"
RAILS_ENV = "production"
RAILS_LOG_LEVEL = "warn"
RAILS_LOG_TO_STDOUT = "enabled"
RAILS_SERVE_STATIC_FILES = "false"
REDIS_URL = "redis://mastodon-3615-computer-redis.internal:6379/?family=6" # Force IPv6 with "family=6"
# REDIS_HOST = "mastodon-3615-computer-redis.internal"
# REDIS_PORT = "6379"
## Storage on S3 also requires secrets named AWS_ACCESS_KEY_ID and
## AWS_SECRET_ACCESS_KEY. If you use this, remove [mounts] below.
S3_ENABLED = "true"
S3_BUCKET = "3615-computer-mastodon"
S3_ALIAS_HOST = "mastodon-files.3615.computer"
S3_ENDPOINT = "https://dfe59bbab9f2a8b244d57744936adfc7.r2.cloudflarestorage.com/"
S3_PERMISSION = "private"
S3_PROTOCOL = "https"
# S3_DISABLE_CHECKSUM_MODE: https://github.com/mastodon/mastodon/pull/26435
S3_DISABLE_CHECKSUM_MODE = "true"

## If you point to Fly here, uncomment the proxy in Caddyfile
# S3_ALIAS_HOST=3615-computer.fly.dev
## Sending email via SMTP also requires secrets
## named SMTP_LOGIN and SMTP_PASSWORD
SMTP_SERVER = "smtp.sendgrid.net"
SMTP_PORT = "587"
SMTP_ENABLE_STARTTLS = "always"
SMTP_FROM_ADDRESS = "mastodon@3615.computer"

## Comment out this section if you use cloud storage
# [mounts]
#   source = "mastodon_uploads"
#   destination = "/opt/mastodon/public/system"

## If you uncomment this to scale up to more VMs,
##   - Remove the entire [mounts] section above
##   - Remove the OVERMIND_FORMATION env line above
##   - Uncomment `processes = ["rails"]` below in [[services]]
# [processes]
#   # If you need more web server workers, scale up this group
#   # by running `fly scale count rails=N
#   rails = "./overmind start -x sidekiq"
#   # If you need to run more sidekiq workers, scale up this group
#   # by running `fly scale count N --group sidekiq`
#   sidekiq = "bash -c 'bundle exec sidekiq -c $MAX_THREADS -q default,8 -q push,6 -q ingress,4 -q mailers,2 -q pull'"
#   # The schedule queue can only ever have one worker process at a time
#   # by running fly scale count 1 --group schedule
#   schedule = "bash -c 'bundle exec sidekiq -c $MAX_THREADS'"

[[statics]]
guest_path = "/opt/mastodon/public"
url_prefix = "/"

[[services]]
# processes = ["rails"]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "15s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
path = "/health"
grace_period = "30s"
interval = "15s"
restart_limit = 0
timeout = "2s"
