app = "mastodon-example-predeploy"

[deploy]
  release_command = "bin/rails db:migrate"

[env]
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "enabled"
  REDIS_HOST = "mastodon-example-redis.internal"
  REDIS_PORT = "6379"
  SKIP_POST_DEPLOYMENT_MIGRATIONS = "true"
