app = "mastodon-example"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  OVERMIND_PROCESSES = "sidekiq"
  MALLOC_ARENA_MAX = "2"
  MAX_THREADS = "5"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "enabled"
  RAILS_SERVE_STATIC_FILES = "false"
  REDIS_HOST = "mastodon-example-redis.internal"
  REDIS_PORT = "6379"
  ## Storage on S3 also requires secrets named
  ## AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
  # S3_ENABLED=true
  # S3_BUCKET=files.example.com
  # S3_ALIAS_HOST=files.example.com
  ## Sending email via SMTP also requires secrets
  ## named SMTP_LOGIN and SMTP_PASSWORD
  # SMTP_SERVER = "smtp.postmarkapp.com"
  # SMTP_PORT = "587"
  # SMTP_ENABLE_STARTTLS = "always"
  # SMTP_FROM_ADDRESS = "admin@mastodon.fly.dev"
